[tools]
# https://mise.jdx.dev/configuration/settings.html#cargo.binstall
cargo-binstall = "latest"

###################
##### AI CLIs #####
###################
"npm:@mariozechner/pi-coding-agent" = "latest"
codex = "latest"
opencode = "latest"

###################
#### Languages ####
###################
go = "1.24"
zig = "latest"

# JavaScript
biome = "2"
bun = "latest"
node = "lts"
pnpm = "10"
yarn = "1"

# Python
python = "3.14"
uv = "latest"

# Rust
"cargo:cargo-edit" = "latest"
"cargo:cargo-lambda" = "latest"
"cargo:cargo-machete" = "latest"
"cargo:cargo-outdated" = "latest"
"cargo:cargo-udeps" = "latest"

####################
####### Cloud ######
####################
"github:unikraft/kraftkit" = "0.12.5"
gcloud = "latest"
github-cli = "latest"

# AWS
"github:runs-on/cli" = "latest"
aws-cli = "2"
aws-sam = "latest"
cfn-lint = "latest"
cli53 = "latest"
granted = "latest"

###################
####### IaC #######
###################
"npm:aws-cdk" = "2"
"npm:cdktf-cli" = "latest"
"npm:wrangler" = "latest"
opentofu = "1"
pulumi = "3"
terraform = "1"

###################
## Observability ##
###################
"github:dev7a/serverless-otlp-forwarder" = { version = "cli/livetrace-v0.2.1" }
"github:hatoo/oha" = "latest"

####################
##### Security #####
####################
age = "latest"
sops = "latest"

###################
#### Utilities ####
###################
bat = "latest"
edit = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
jq = "latest"
ripgrep = "latest"
yq = "latest"

[settings]
idiomatic_version_file_enable_tools = []
