# ~/.config/fish/config.fish
# Ported from ~/.bashrc and ~/.bash_aliases on 2026-07-25.
# bash stays the login shell; this file drives interactive fish sessions.

# Silence fish's built-in two-line greeting. Defining it empty is enough:
# fish_greeting only builds the default text when the variable is unset.
set -g fish_greeting

### MISE (MUST LOAD FIRST)
if status is-interactive
    mise activate fish | source
else
    mise activate fish --shims | source
end

# `mise activate` defines its own `mise` function, which already handles the
# `deactivate`/`shell`/`sh` eval passthrough that _mise_passthrough did in bash.
# Copy it, then wrap it so a bare `mise upgrade` still skips kiro-cli.
# The `not functions -q __mise_activate` guard matters: without it, re-sourcing
# this file would copy the wrapper below onto itself and recurse forever.
if functions -q mise; and not functions -q __mise_activate
    functions --copy mise __mise_activate
    function mise --wraps mise -d 'mise, with kiro-cli excluded from `mise upgrade`'
        # aqua's registry entry for kiro.dev/kiro-cli has no repo_owner/repo_name,
        # so every version lookup emits two warnings. Exclude it from upgrades
        # unless it was named explicitly.
        #
        # NOTE: --exclude matches the installed tool name (`kiro-cli`). The
        # backend-qualified id (`aqua:kiro.dev/kiro-cli`) silently no-ops.
        if test (count $argv) -ge 1; and test "$argv[1]" = upgrade
            and not string match -q '*kiro-cli*' -- $argv[2..]
            command mise upgrade --exclude kiro-cli $argv[2..]
            return $status
        end
        __mise_activate $argv
    end
end

### MISE COMPLETIONS
# mise's completion script is a thin wrapper: it shells out to the `usage` CLI
# (usage.jdx.dev, same author) on every TAB, against a spec mise dumps for itself.
# `mise completion fish` bakes mise's own version into that spec's filename, so
# after a `mise self-update` the script keeps reading the previous version's cached
# spec and silently completes stale commands until it is regenerated by hand.
# Resolving the path at completion time instead makes a mise upgrade self-healing.
#
# This lives here rather than in ~/.config/fish/completions/ because that directory
# is deliberately empty: config.fish is the only fish file the os-configs sync
# captures, so anything left there is lost on a rebuild.
if status is-interactive
    function __mise_complete -d 'completion candidates for mise, via the usage CLI'
        type -q usage; or return

        set -l cache_dir $HOME/.cache/usage
        test -n "$XDG_CACHE_HOME"; and set cache_dir $XDG_CACHE_HOME/usage

        # `mise --version` prints "2026.8.10 linux-x64 (2026-08-20)"; usage names the
        # spec after the first field with dots as underscores. A newer mise therefore
        # asks for a filename that does not exist yet, which rebuilds the cache.
        # NOTE: not `version` — that is a fish special variable, and `set -l version`
        # fails, leaving $version as fish's own version and keying the cache on it.
        set -l mise_version (command mise --version 2>/dev/null | string split -f1 ' ' | string replace -a . _)
        test -n "$mise_version"; or return
        set -l spec $cache_dir/usage__usage_spec_mise_$mise_version.spec

        if not test -f $spec
            mkdir -p -m 700 $cache_dir; or return
            # Drop specs left by versions that are long gone, as mise's own script does.
            find $cache_dir -maxdepth 1 -name 'usage__usage_spec_mise_*.spec' -type f -mtime +30 -delete 2>/dev/null
            command mise usage | string collect >$spec; or return
        end

        # fish 3.7 has no `commandline -x`; -o is its equivalent, deprecated in fish 4.
        # Probing per call rather than once at startup means a fish upgrade needs no edit.
        if commandline -x >/dev/null 2>&1
            command usage complete-word --shell fish -f $spec -- (commandline -xpc) (commandline -t)
        else
            command usage complete-word --shell fish -f $spec -- (commandline -opc) (commandline -t)
        end
    end

    complete -xc mise -a '(__mise_complete)'
end

### PATH
# fish_add_path prepends, so the LAST call ends up first. Order below yields
# ~/.local/bin, ~/bin, ~/.cargo/bin, then mise's paths - matching bash, but
# without bash's duplicate ~/.local/bin. Non-existent dirs are skipped, so
# ~/.bun/bin (which does not exist yet) is simply picked up if it appears.
set -gx BUN_INSTALL $HOME/.bun
fish_add_path -g $BUN_INSTALL/bin
fish_add_path -g $HOME/.cargo/bin
fish_add_path -g $HOME/bin
fish_add_path -g $HOME/.local/bin

### PATH GUARD (MUST LOAD AFTER MISE)
# `mise hook-env` runs on every prompt and before every command, and it rebuilds
# PATH from scratch with the tool install dirs in front. That puts mise's own `gh`
# ahead of the ~/.local/bin wrapper, so anything resolving `gh` through PATH gets
# an unauthenticated gh - `dome` shells out to `gh auth status` and refuses to run.
# The fish_add_path calls above run once at startup and cannot hold the position.
# Event handlers fire in definition order, so re-asserting here, after mise's
# __mise_env_eval_on_prompt and __mise_env_eval_2, wins on both events.
#
# Added after a vendor CLI that shells out to `gh auth status` refused to run, but
# it is not specific to that tool: it protects anything resolving `gh` through
# PATH, so it stays useful regardless of which project surfaced it.
function __local_bin_first -d 'keep ~/.local/bin ahead of mise install dirs'
    if test "$PATH[1]" != "$HOME/.local/bin"
        set -gx PATH $HOME/.local/bin (string match -v -- $HOME/.local/bin $PATH)
    end
end

function __local_bin_first_on_prompt --on-event fish_prompt -d 'see __local_bin_first'
    __local_bin_first
end

function __local_bin_first_on_preexec --on-event fish_preexec -d 'see __local_bin_first'
    __local_bin_first
end

### OH MY POSH
if status is-interactive
    oh-my-posh init fish --strict --config $HOME/.config/oh-my-posh/themes/multiverse-neon.omp.json | source
end

### BROWSER
# Many CLIs check $BROWSER first and just print the URL when it is empty, which is
# why so many of them refused to open anything. Point it at xdg-open rather than a
# browser directly, so one place decides which browser opens: the default handler
# registered with xdg-settings. That resolves to wsl-explorer.desktop ->
# /mnt/c/WINDOWS/explorer.exe, handing the URL to the Windows default browser via
# WSL interop. explorer.exe is a Windows built-in, so this needs no wslu, which was
# archived upstream on 2025-03-01 and removed from this machine.
#
# xdg-open strips itself out of $BROWSER internally, so this cannot recurse.
# Caveat: explorer.exe returns non-zero even on success and xdg-open passes that
# through (exit 4). Launches are reliable; only the status is wrong.
#
# To switch to a WSL-native browser, repoint the handler rather than editing here:
#   xdg-settings set default-web-browser google-chrome.desktop
set -gx BROWSER xdg-open

### GPG
# pinentry-curses draws its prompt on a terminal, and gpg-agent needs to be told
# which one. Without this, signing fails with "Inappropriate ioctl for device".
set -gx GPG_TTY (tty)

### ALIASES
alias ll 'ls -alF'
alias la 'ls -A'
alias l 'ls -CF'
alias pj 'npx projen'

function grep --wraps grep -d 'grep, with colour'
    command grep --color=auto $argv
end

### GIT / WORKTREES
function cpr -d 'Check out a GitHub PR into a sibling worktree and cd into it'
    set -l pr_number $argv[1]
    set -l remote origin
    test (count $argv) -ge 2; and set remote $argv[2]

    if test -z "$pr_number"
        echo "Usage: cpr <PR_NUMBER> [REMOTE]" >&2
        return 2
    end
    if not command -q gh
        echo "cpr: missing gh (GitHub CLI)." >&2
        return 127
    end

    set -l branch (gh pr view $pr_number --json headRefName -q .headRefName); or return
    # Slashes are illegal in a sibling directory name.
    set -l worktree_dir ../(string replace -a / - -- $branch)

    git fetch $remote $branch; or return
    git worktree add $worktree_dir $branch; or return
    cd $worktree_dir; or return
    printf 'Switched to new worktree for PR #%s: %s\n' $pr_number $branch
end

### GRANTED
# granted ships a native fish entrypoint next to the `assume` shim.
function assume --wraps assume -d 'granted: assume an AWS role'
    source (dirname (mise which assume))/assume.fish $argv
end

### PYTHON VENVS (mise-managed)
function mkvenv -d 'Add a mise.local.toml that auto-activates ./.venv (or a given path)'
    set -l venv_path .venv
    if test (count $argv) -gt 0
        set venv_path $argv[1]
    end

    if test -e mise.local.toml
        echo "mkvenv: mise.local.toml already exists - edit it by hand." >&2
        return 1
    end

    printf '[env]\n_.python.venv = { path = "%s", create = true }\n' $venv_path >mise.local.toml
    mise trust -q .
    echo "mkvenv: mise.local.toml -> $venv_path (cd out and back in to activate)"
end
