model = "gpt-5.5"
model_reasoning_effort = "high"
plan_mode_reasoning_effort = "xhigh"
personality = "pragmatic"
approvals_reviewer = "user"

[features]
fast_mode = false
goals = true
memories = true

[notice]
hide_full_access_warning = true
hide_rate_limit_model_nudge = true

[tui.model_availability_nux]
"gpt-5.5" = 4

# ====================
# Plugins
# ====================
[marketplaces.agent-toolkit-for-aws]
last_updated = "2026-05-19T14:55:48Z"
last_revision = "ba1cc8ca4f063d88ca40c6acf3f670e6321b7a7f"
source_type = "git"
source = "https://github.com/aws/agent-toolkit-for-aws.git"

[plugins."aws-agents@agent-toolkit-for-aws"]
enabled = true

# ====================
# MCP Servers
# ====================
[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]
enabled = false

# ====================
# Projects
# ====================
[projects."/home/user/.agents"]
trust_level = "trusted"

[projects."/home/user/.codex"]
trust_level = "trusted"

[projects."/home/user/.config"]
trust_level = "trusted"

[projects."/home/user/github"]
trust_level = "trusted"

[projects."/home/user/work-pmt"]
trust_level = "trusted"
