[registry]
global-credential-providers = ["cargo:token", "cargo:macos-keychain"]

[registries.crates-io]
protocol = "sparse"

[registries.ocr-labs]
index = "ssh://git@ssh.shipyard.rs/ocr-labs/crate-index.git"

[net]
git-fetch-with-cli = true
